# Generated by Django 5.2.10 on 2026-02-06 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('properties', '0007_property_area_property_bathrooms_property_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
    ]
