# Generated by Django 5.2.10 on 2026-02-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
