# Generated by Django 5.2.10 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_area_property_bathrooms_property_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(
                choices=[('buy', 'Buy'), ('rent', 'Rent'), ('lease', 'Lease')],
                default='buy',
                max_length=20,
            ),
        ),
    ]
