# Generated by Django 5.2.10 on 2026-01-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertyimage_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/main/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('villa', 'Villa'), ('plot', 'Plot'), ('house', 'house')], max_length=20),
        ),
    ]
