# Generated by Django 5.2.10 on 2026-01-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_image_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment / Flat'), ('villa', 'Villa'), ('building', 'Building'), ('complex', 'Residential Complex'), ('commercial', 'Commercial Property'), ('land', 'Land / Plot')], max_length=20),
        ),
    ]
